fix: bridge module cli
realiotech/realio-network pull request #185
Opened 2024-12-30 10:22 UTC by trinitys7

2024-12-31 14:03 UTC, jiujiteiro approved these changes

2025-01-27 23:51 UTC, jiujiteiro reviewed
What is the state of this pr?

2025-01-28 00:00 UTC, jiujiteiro requested changes
I think this is not backwards compatible so we would need a planned upgrade. Also can you please add changes to the change log?

2025-02-06 19:50 UTC, jiujiteiro commented
@catShaark bumping

2025-02-06 19:55 UTC, jiujiteiro commented
lets update and merge this in.

2025-03-05 15:50 UTC, hieuvubk approved these changes
LGTM, let merge that then we can fix the msg signer err I think

2025-03-05 15:50 UTC, hieuvubk commented on proto/realionetwork/bridge/v1/tx.proto
> +  option (cosmos.msg.v1.signer) = "authority";
@catShaark This will fix msg signer err

2025-03-05 15:56 UTC, hieuvubk commented on proto/realionetwork/bridge/v1/tx.proto
> +  option (cosmos.msg.v1.signer) = "authority";
@jiujiteiro

2025-03-05 16:29 UTC, merged